[project]
name = "coursework-1"
version = "0.1.0"
description = ""
authors = [
    {name = "Andrey Kazantsev",email = "andrey.kazantsev.1997@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "mypy (>=2.1.0,<3.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "requests (>=2.34.2,<3.0.0)"
]

[tool.black]
line-length = 119
target-version = ['py314']

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length = 119
[dependency-groups]
lint = [
    "pandas-stubs (>=3.0.0.260204,<4.0.0.0)"
]
[tool.mypy]
disallow_untyped_defs = false
no_implicit_optional = false
warn_return_any = false
exclude = "venv"
mypy_path = "."
explicit_package_bases = true
disable_error_code = ["operator", "arg-type"]